MAX_LENGTH_INGREDINET_NAME = 150
MAX_LENGHT_MEASUREMENT_LENGTH = 15
MAX_LENGTH_TAG_NAME = 50
MAX_LENGTH_RECIPE_NAME = 256
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440
MIN_AMOUNT = 1
MAX_AMOUNT = 2000
