# Generated by Django 3.2.3 on 2024-07-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'default_related_name': 'subscription', 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
