# Generated by Django 3.2.3 on 2024-07-20 20:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author__exact', django.db.models.expressions.F('user')), _negated=True), name='subscribe_to_yourself'),
        ),
    ]
