# Generated by Django 3.2.3 on 2024-07-20 21:16

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240720_2026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscribe_to_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('user')), _negated=True), name='subscribe_to_yourself'),
        ),
    ]
