# Generated by Django 3.2.3 on 2024-07-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240720_2131'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='subscribe_to_yourself',
        ),
    ]
